#!/bin/sh

exec 2>&1
sv check weston > /dev/null || exit 1
sv check nocturne-ui > /dev/null || exit 1
sv check nocturned > /dev/null || exit 1
curl -fs http://localhost:5000/info > /dev/null 2>&1 || exit 1

export XDG_RUNTIME_DIR="/run/wayland/"
export XDG_CACHE_HOME="/var/cache"
export BREAKPAD_DUMP_LOCATION="/var/cache/chrome_storage/Crash Reports"

exec /usr/bin/chromium-browser/chrome --no-sandbox --in-process-gpu --remote-debugging-port=2222 --user-data-dir=/var/cache/chrome_storage --kiosk --disable-pinch --allow-file-access-from-files --ignore-certificate-errors --enable-experimental-web-platform-features --app=http://localhost:80 > /dev/null 2>&1
